import { NextResponse } from 'next/server';
import { reserveDriftMonitor, migrationProposalEngine, reserveMonitor, backingVerifier } from '@/protocol/treasury-v2';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/**
 * GET /api/treasury/insights
 *
 * Surfaces three treasury wiring-roadmap deliverables in one call:
 *
 *   I1 — per-currency reserve drift (with alarm threshold)
 *   D1 — per-corridor stablecoin vs twin composition
 *   D2 — pending migration proposals (never executed)
 *
 * This endpoint is read-only. It does not mutate any state. The drift
 * monitor and migration proposal engine are in-memory singletons — their
 * state survives across requests within a single Next.js server process.
 *
 * Response shape:
 *   {
 *     drift:    DriftStatus[]         // I1
 *     composition: CorridorComposition[] // D1
 *     proposals: MigrationProposal[]  // D2
 *     summary: { driftAlarms, twinPctAvg, pendingProposals, ts }
 *   }
 */
export async function GET() {
  // I1: per-currency drift status. We need current balances from the
  // reserve monitor (singleton). For currencies the monitor doesn't
  // know about, drift is 0 with no alarm.
  const reserves = reserveMonitor.allReserves();
  const balances = new Map<string, number>();
  for (const r of reserves) {
    balances.set(r.currency, r.balance);
  }
  // Seed starting balances for the drift monitor if not set.
  for (const r of reserves) {
    if (reserveDriftMonitor.startingBalance(r.currency) === 0 && r.balance > 0) {
      reserveDriftMonitor.setStartingBalance(r.currency, r.balance);
    }
  }
  const drift = reserveDriftMonitor.statusAll(balances);

  // D1: per-corridor composition. Derive corridors from backing states
  // (each TWIN<CCY> backing state corresponds to a corridor that touches CCY).
  // For each tracked twin token, report the composition.
  const backingStates = backingVerifier.all();
  const composition = migrationProposalEngine.allCompositions();

  // If no compositions have been recorded yet, seed them from the backing
  // states so the dashboard has something to show on first load.
  if (composition.length === 0 && backingStates.length > 0) {
    for (const bs of backingStates) {
      // TWIN<CCY> → CCY. Treat the corridor as "USD:CCY" (cross-border into CCY).
      const toCurrency = bs.assetCode.startsWith('TWIN') ? bs.assetCode.slice(4) : bs.assetCode;
      const reserve = reserveMonitor.getReserve(toCurrency);
      const destFiatReserve = reserve?.balance ?? 0;
      // Twin capacity = circulating supply (1:1 backed).
      // Stablecoin capacity = approximated from the reserve's available amount.
      const twinCapacity = bs.circulating;
      const stablecoinCapacity = reserve?.available ?? 0;
      migrationProposalEngine.recordComposition({
        corridor: `USD:${toCurrency}`,
        fromCurrency: 'USD',
        toCurrency,
        twinCapacity,
        stablecoinCapacity,
        destinationFiatReserve: destFiatReserve,
      });
    }
  }
  const finalComposition = migrationProposalEngine.allCompositions();

  // D2: pending migration proposals (these are generated by proposeForAll()
  // or by an explicit propose call. They are never executed by this endpoint.)
  const proposals = migrationProposalEngine.pendingProposals();

  // Summary
  const driftAlarms = drift.filter((d) => d.alarm).length;
  const twinPctAvg = finalComposition.length > 0
    ? finalComposition.reduce((s, c) => s + c.twinPct, 0) / finalComposition.length
    : 0;
  const pendingProposals = proposals.length;

  return NextResponse.json({
    drift,
    composition: finalComposition,
    proposals,
    summary: {
      driftAlarms,
      twinPctAvg: Math.round(twinPctAvg * 10000) / 10000,
      pendingProposals,
      totalReserves: reserves.length,
      totalBackingStates: backingStates.length,
      ts: Date.now(),
    },
  });
}

/**
 * POST /api/treasury/insights
 *
 * Body:
 *   { action: 'proposeMigrations', inputs: CompositionInput[] }
 *     → generates D2 proposals for the given corridors (never executes).
 *
 *   { action: 'reviewProposal', id: string, decision: 'approved' | 'rejected', note?: string }
 *     → records a human review on a proposal. Does NOT execute. Execution
 *       would go through a separate treasury operation via the dispatcher.
 *
 *   { action: 'seedDrift', balances: Record<string, number> }
 *     → seeds starting balances for the drift monitor (call once when
 *       initialising reserves).
 */
export async function POST(req: Request) {
  let body: any = {};
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }

  const action = typeof body?.action === 'string' ? body.action : '';

  if (action === 'proposeMigrations') {
    const inputs = Array.isArray(body?.inputs) ? body.inputs : [];
    const valid = inputs.filter((i: any) =>
      typeof i?.corridor === 'string' &&
      typeof i?.fromCurrency === 'string' &&
      typeof i?.toCurrency === 'string' &&
      typeof i?.twinCapacity === 'number' &&
      typeof i?.stablecoinCapacity === 'number' &&
      typeof i?.destinationFiatReserve === 'number'
    );
    const proposals = migrationProposalEngine.proposeForAll(valid);
    return NextResponse.json({
      generated: proposals.length,
      proposals,
      note: 'Proposals are NOT executed. A human must review and approve before any treasury operation.',
    });
  }

  if (action === 'reviewProposal') {
    const id = typeof body?.id === 'string' ? body.id : '';
    const decision = body?.decision === 'approved' || body?.decision === 'rejected' ? body.decision : null;
    if (!id || !decision) {
      return NextResponse.json({ error: 'id and decision (approved|rejected) are required' }, { status: 400 });
    }
    const note = typeof body?.note === 'string' ? body.note.slice(0, 500) : undefined;
    const proposal = migrationProposalEngine.reviewProposal(id, decision, note);
    if (!proposal) {
      return NextResponse.json({ error: 'Proposal not found' }, { status: 404 });
    }
    return NextResponse.json({
      reviewed: true,
      proposalId: id,
      decision,
      note: 'Review recorded. The proposal was NOT executed. Execution requires a separate treasury operation via the dispatcher.',
    });
  }

  if (action === 'seedDrift') {
    const balances = body?.balances && typeof body.balances === 'object' ? body.balances : {};
    for (const [currency, balance] of Object.entries(balances)) {
      if (typeof balance === 'number' && Number.isFinite(balance) && balance > 0) {
        reserveDriftMonitor.setStartingBalance(currency, balance);
      }
    }
    return NextResponse.json({
      seeded: Object.keys(balances).length,
      note: 'Starting balances recorded for drift monitoring.',
    });
  }

  return NextResponse.json({ error: `Unknown action: ${action || '(none)'}` }, { status: 400 });
}
