{{/* PaySwap — Secret (placeholder values; in prod, source from Vault / external-secrets) */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "payswap.fullname" . }}-secrets
  namespace: {{ include "payswap.namespace" . }}
  labels:
    {{- include "payswap.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.secrets }}
stringData:
  {{- range $key, $val := . }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
