import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import {
  requireAdminSession,
  forbidden,
} from '@/lib/api-auth';
import { paymentService } from '@/services';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/**
 * POST /api/admin/simulate/payment — generate a synthetic test payment.
 *
 * NH-3 FIX: Now dispatches through paymentService → executionPlanner →
 * dispatcher → invariants → event store → ledger. Previously bypassed
 * the kernel with direct db.payment.create().
 *
 * Requires ADMIN or SUPER_ADMIN role.
 */
export async function POST() {
  const adminSession = await requireAdminSession();
  if (!adminSession) return forbidden();

  // Pick the first active merchant so the test payment has a valid FK.
  const merchant = await db.merchant.findFirst({
    where: { deletedAt: null },
    orderBy: { createdAt: 'asc' },
  });
  if (!merchant) {
    return NextResponse.json(
      { error: 'No merchant available to attach test payment' },
      { status: 400 },
    );
  }

  const amount = Math.round((10 + Math.random() * 990) * 100) / 100;
  const methods = ['MOBILE_MONEY', 'CARD', 'BANK_TRANSFER'];
  const method = methods[Math.floor(Math.random() * methods.length)];

  try {
    const payment = await paymentService.create({
      merchantId: merchant.id,
      amount,
      currency: merchant.currency,
      method,
      description: '[SIMULATION] Test payment generated by admin runtime',
      environment: 'sandbox',
      actorId: (adminSession.user as any).id,
      success: true,
    });

    await db.auditLog.create({
      data: {
        userId: (adminSession.user as any).id,
        action: 'SIMULATE.PAYMENT',
        resourceType: 'Payment',
        resourceId: payment.id,
        result: 'SUCCESS',
        details: JSON.stringify({ reference: payment.reference, amount, currency: merchant.currency }),
      },
    });

    return NextResponse.json({
      ok: true,
      payment,
      message: `Created test payment ${payment.reference} for ${amount} ${merchant.currency}`,
    });
  } catch (e) {
    return NextResponse.json(
      { ok: false, error: e instanceof Error ? e.message : 'Simulation failed' },
      { status: 500 },
    );
  }
}
