import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import {
  requireAdminSession,
  forbidden,
} from '@/lib/api-auth';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/**
 * POST /api/admin/simulate/payment — generate a synthetic test payment.
 *
 * Requires ADMIN or SUPER_ADMIN role.
 */
export async function POST() {
  const adminSession = await requireAdminSession();
  if (!adminSession) return forbidden();

  // Pick the first active merchant so the test payment has a valid FK.
  const merchant = await db.merchant.findFirst({
    where: { deletedAt: null },
    orderBy: { createdAt: 'asc' },
  });
  if (!merchant) {
    return NextResponse.json(
      { error: 'No merchant available to attach test payment' },
      { status: 400 },
    );
  }

  const amount = Math.round((10 + Math.random() * 990) * 100) / 100;
  const reference = `SIM-PAY-${Date.now().toString(36).toUpperCase()}`;
  const methods = ['MOBILE_MONEY', 'CARD', 'BANK_TRANSFER'];
  const method = methods[Math.floor(Math.random() * methods.length)];

  const payment = await db.payment.create({
    data: {
      merchantId: merchant.id,
      amount,
      currency: merchant.currency,
      status: 'COMPLETED',
      method,
      reference,
      description: '[SIMULATION] Test payment generated by admin runtime',
      fee: Math.round(amount * 0.015 * 100) / 100,
      netAmount: Math.round(amount * 0.985 * 100) / 100,
      fxRate: 1,
      settledAt: new Date(),
    },
  });

  await db.auditLog.create({
    data: {
      userId: (adminSession.user as any).id,
      action: 'SIMULATE.PAYMENT',
      resourceType: 'Payment',
      resourceId: payment.id,
      result: 'SUCCESS',
      details: JSON.stringify({ reference, amount, currency: merchant.currency }),
    },
  });

  return NextResponse.json({
    ok: true,
    payment,
    message: `Created test payment ${reference} for ${amount} ${merchant.currency}`,
  });
}
