import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { db } from '@/lib/db';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export async function POST() {
  const session = await getServerSession(authOptions);
  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }
  const roles = (session.user as any)?.roles as string[] | undefined;
  if (!roles || !roles.some((r) => ['ADMIN', 'SUPER_ADMIN'].includes(r))) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
  }

  // Pick the first active merchant so the test payment has a valid FK.
  const merchant = await db.merchant.findFirst({
    where: { deletedAt: null },
    orderBy: { createdAt: 'asc' },
  });
  if (!merchant) {
    return NextResponse.json(
      { error: 'No merchant available to attach test payment' },
      { status: 400 },
    );
  }

  const amount = Math.round((10 + Math.random() * 990) * 100) / 100;
  const reference = `SIM-PAY-${Date.now().toString(36).toUpperCase()}`;
  const methods = ['MOBILE_MONEY', 'CARD', 'BANK_TRANSFER'];
  const method = methods[Math.floor(Math.random() * methods.length)];

  const payment = await db.payment.create({
    data: {
      merchantId: merchant.id,
      amount,
      currency: merchant.currency,
      status: 'COMPLETED',
      method,
      reference,
      description: '[SIMULATION] Test payment generated by admin runtime',
      fee: Math.round(amount * 0.015 * 100) / 100,
      netAmount: Math.round(amount * 0.985 * 100) / 100,
      fxRate: 1,
      settledAt: new Date(),
    },
  });

  await db.auditLog.create({
    data: {
      userId: (session.user as any).id,
      action: 'SIMULATE.PAYMENT',
      resourceType: 'Payment',
      resourceId: payment.id,
      result: 'SUCCESS',
      details: JSON.stringify({ reference, amount, currency: merchant.currency }),
    },
  });

  return NextResponse.json({
    ok: true,
    payment,
    message: `Created test payment ${reference} for ${amount} ${merchant.currency}`,
  });
}
