import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import {
  requireAdminSession,
  forbidden,
} from '@/lib/api-auth';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const ALERT_TYPES = [
  'VELOCITY',
  'STRUCTURING',
  'HIGH_RISK_CORRIDOR',
  'UNUSUAL_AMOUNT',
  'SANCTIONS_HIT',
];
const SEVERITIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];

/**
 * POST /api/admin/simulate/aml — generate a synthetic AML alert.
 *
 * Requires ADMIN or SUPER_ADMIN role.
 */
export async function POST() {
  const adminSession = await requireAdminSession();
  if (!adminSession) return forbidden();

  const merchant = await db.merchant.findFirst({
    where: { deletedAt: null },
    orderBy: { createdAt: 'asc' },
  });
  if (!merchant) {
    return NextResponse.json(
      { error: 'No merchant available to attach AML alert' },
      { status: 400 },
    );
  }

  const alertType = ALERT_TYPES[Math.floor(Math.random() * ALERT_TYPES.length)];
  const severity = SEVERITIES[Math.floor(Math.random() * SEVERITIES.length)];
  const score = Math.round((0.4 + Math.random() * 0.6) * 100) / 100;

  const alert = await db.aMLAlert.create({
    data: {
      entityType: 'MERCHANT',
      entityId: merchant.id,
      alertType,
      severity,
      score,
      details:
        '[SIMULATION] Synthetic AML alert generated by admin runtime for testing the compliance pipeline.',
      status: 'OPEN',
      // Simulations are always sandbox traffic — never touch live compliance queues.
      environment: 'sandbox',
    },
  });

  await db.auditLog.create({
    data: {
      userId: (adminSession.user as any).id,
      action: 'SIMULATE.AML_ALERT',
      resourceType: 'AMLAlert',
      resourceId: alert.id,
      result: 'SUCCESS',
      details: JSON.stringify({ alertType, severity, score }),
    },
  });

  return NextResponse.json({
    ok: true,
    alert,
    message: `Created ${severity} ${alertType} AML alert (score ${score})`,
  });
}
