import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { db } from '@/lib/db';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export async function POST() {
  const session = await getServerSession(authOptions);
  if (!session) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }
  const roles = (session.user as any)?.roles as string[] | undefined;
  if (!roles || !roles.some((r) => ['ADMIN', 'SUPER_ADMIN'].includes(r))) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
  }

  const merchant = await db.merchant.findFirst({
    where: { deletedAt: null },
    orderBy: { createdAt: 'asc' },
  });
  if (!merchant) {
    return NextResponse.json(
      { error: 'No merchant available to attach test payout' },
      { status: 400 },
    );
  }

  const amount = Math.round((50 + Math.random() * 1950) * 100) / 100;
  const reference = `SIM-PO-${Date.now().toString(36).toUpperCase()}`;
  const methods = ['MOBILE_MONEY', 'BANK_TRANSFER'];
  const method = methods[Math.floor(Math.random() * methods.length)];

  const payout = await db.payout.create({
    data: {
      merchantId: merchant.id,
      method,
      sourceAmount: amount,
      sourceAsset: merchant.currency,
      sourceCurrency: merchant.currency,
      destinationCurrency: merchant.currency,
      destination: 'SIM-RECIPIENT',
      fxRate: 1,
      feeBps: 50,
      fee: Math.round(amount * 0.005 * 100) / 100,
      netAmount: Math.round(amount * 0.995 * 100) / 100,
      status: 'COMPLETED',
      reason: '[SIMULATION] Test payout generated by admin runtime',
      processedAt: new Date(),
      completedAt: new Date(),
    },
  });

  await db.auditLog.create({
    data: {
      userId: (session.user as any).id,
      action: 'SIMULATE.PAYOUT',
      resourceType: 'Payout',
      resourceId: payout.id,
      result: 'SUCCESS',
      details: JSON.stringify({ reference, amount, currency: merchant.currency }),
    },
  });

  return NextResponse.json({
    ok: true,
    payout,
    message: `Created test payout ${reference} for ${amount} ${merchant.currency}`,
  });
}
